repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: [
          'numpy',
          'types-setuptools',
          'typing_extensions',
          'mypy_extensions',
        ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
